load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "gtest",    # External project that will be used.
    remote = "https://github.com/google/googletest",
    branch = "v1.10.x",
)

# Using Http to import External folder (Not woking very well to Google Test)
# load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
# http_archive(
#     name = "gtest",
#     url = "https://github.com/google/googletest/archive/release-1.10.0.zip",
#     sha256 = "94c634d499558a76fa649edb13721dce6e98fb1e7018dfaeba3cd7a083945e91",
#     build_file = "@//:gtest.BUILD",
#     strip_prefix = "googletest-release-1.10.0/googletest"
# )