cc_library(
    name = "random-lib",
    srcs = ["src/RandomPrint.cpp"],
    hdrs = ["include/RandomPrint.h"],
    copts = ["-Ilibs/lib02/include"],    # Used to define an include path of the library.
    visibility = ["//visibility:public"]
)