load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "gtest",    # External project that will be used.
    remote = "https://github.com/google/googletest",
    branch = "v1.10.x",
)