cc_library(
    name = "special-lib",
    srcs = ["src/SpecialPrint.cpp"],
    hdrs = ["include/SpecialPrint.h"],
    copts = ["-Ilibs/lib01/include"],        # Used to define an include path of the library.
    visibility = ["//visibility:public"]
)