cc_library(
    name = "rand",
    srcs = ["rand.cc"],
    hdrs = ["rand.h"],
    visibility = ["//main:__pkg__"], # Visible to every package inside main folder, you can add more folders in the list.
)